### ISSUE TITLE
[Bug] Install button will turn grey if you press back when installing.

### ISSUE THREAD

**Issue by Aws0mee** [rauenzi/BBDInstaller#12]
**Describe the Bug**
The install button on the installer will turn grey if you select where you want to install and then go back. It saves the state of the check mark, but assumes that the installer is unable to install. It's not a big problem at all, but I thought I should let it be known as I found it within 30 seconds of installing the program.

**To Reproduce**
Open Installer, click agree. Select install. Now, choose the discord you want to install to. Press back, and then go back to install and you will see the install button will be greyed out and the discord you chose to install it to will still be checked.

**Expected Behavior**
You will be able to press install after hitting the back button, and reentering that part of the menu.

**Screenshots**
I think it's simple enough, I can provide some if needed.

**Discord Version**
Applies to the launcher, not discord version.

**Additional Context**
None.

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
