### ISSUE TITLE
Better Discord not starting with discord launch

### ISSUE THREAD

**Issue by OMeguminO** [rauenzi/BBDInstaller#13]
Basically I have to repair and reinstall Better Discord every time when restarting my pc. Any way to fix this? Basically my discord auto launches when my pc starts, could this have to do with the problem? Thank you in advance

**Comment by ToRRent1812** [comment]
Same issue. Sometimes Ctrl+R helps.

**Comment by tropicaaal** [comment]
![image](https://user-images.githubusercontent.com/42101043/100394898-622c3980-3004-11eb-8497-f578f1a88256.png)

**Comment by ajaykaps** [comment]
I found a workaround for this,
1. Disable open discord at startup in discord app
2. Go to %appdata%\Local\Discord\app-0.0.### (### being the latest app version, mine works with 0.308 and not 0.309)
3. Create a shortcut of Discord.exe and move it to windows startup folder.

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
