### ISSUE TITLE
Предложени

### ISSUE THREAD

**Issue by fan2000pro** [rauenzi/BBDInstaller#17]
Предлогаю сделать версию для пользователей смартфонов так как таких же приятных фонов не хвотает😘

**Comment by litecave** [comment]
🤦, ало чел, не хочу говорить что ты дурачок, но всё таки. АЛО, РАЗРАБЫ АНГЛОГОВОРЯЩИЕ, **_ОНИ РУССКИЙ НЕ ЗНАЮТ!_** Пожалуйсто, пиши грамотней и переводи "предложения свои" на английский, через те же Яндекс.Переводчик/Google Translate...

Можешь закрывать ошибку так как Issue - ошибка.

**Comment by ghost** [comment]
чел, ты... Для чего существует тег enhancement? К тому же ты сам не очень пишешь. А что насчет BetterDiscord на телефоны, рекомендую посмотреть на Bluecord или Cut the Cord, хорошие альтернативы. BetterDiscord на телефонах тупо невозможен, и я надеюсь вы это понимаете (Mobile Discord написан на React Native)

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
