### ISSUE TITLE
Installer does not respect the "Restart All Discord Instances" option.

### ISSUE THREAD

**Issue by doqfgc** [rauenzi/BBDInstaller#21]
When using either the Install or Repair options in the installer, installer will kill Discord processes regardless of whether or not "Restart All Discord Instances" is checked. Discord instances should not be killed if this option is unchecked, or the option should be removed.

**Comment by nikolololololol** [comment]
WHEN I DOWNLOAD THE ZIP FILE IT IS NOT WORKING AND THE ''BANDAGEBD'' PULL UP DOESNT SHOW

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
