### ISSUE TITLE
PTB no longer working with BBD

### ISSUE THREAD

**Issue by Dethkiller15** [rauenzi/BBDInstaller#23]
I always use PTB (cuz I can) and today I see that it got a somewhat large update, and now I am unable to get it working again. I have tried reinstalling it several times but to no avail. I went back to Stable and everything works fine. I think soon whatever they did to PTB will move to Stable.

**Comment by Bluetinity** [comment]
It's no longer working with any of the discord builds

**Comment by Two-Tone** [comment]
Can confirm that it doesn't work. As a precaution I have a backup of my Discord Stable install, deleted update.exe, and set the folder to read only. I suggest doing that for Stable if you can.

**Comment by Dethkiller15** [comment]
> Can confirm that it doesn't work. As a precaution I have a backup of my Discord Stable install, deleted update.exe, and set the folder to read only. I suggest doing that for Stable if you can.

Could you tell me how to do that? I looked into doing the same but I could not find the propper way to do that... do I make both the local and roaming folders read only? I did try but the update.exe is needed in order to launch discord for me.

**Comment by Two-Tone** [comment]
I did it just for the Local folder. It looks like Roaming is a temp folder and setting it to read only might break Discord while it's running.  I have had no issues with update.exe being missing

**Comment by Two-Tone** [comment]
Alternatively to deleting update.exe would be renaming it or moving it to a different folder to not outright lose it.

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
