### ISSUE TITLE
No Longer Working with PTB

### ISSUE THREAD

**Issue by tealyt** [rauenzi/BBDInstaller#25]
It was and then there was an update and now it isnt no matter what i do

**Comment by tealyt** [comment]
ok it doesnt work with any of the 3 versions of discord

**Comment by Bluetinity** [comment]
yup, same

**Comment by SkReintjens** [comment]
same

**Comment by Wolf-ON** [comment]
Duplicate of #23

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
