### ISSUE TITLE
Can't See New Installer's checkboxes 

### ISSUE THREAD

**Issue by armoha** [rauenzi/BBDInstaller#3]
![image](https://user-images.githubusercontent.com/16814706/48661662-00ea3b00-eab9-11e8-9749-923d7f12f791.png)
(unchecked state)

![image](https://user-images.githubusercontent.com/16814706/48661669-2119fa00-eab9-11e8-8f2d-36be384a5074.png)
(checked)

I knew there are checkboxes from rauenzi/BetterDiscordApp#106. I can't see the checkbox but can click text and proceed. I'm using Windows 10 and Display Settings: Scaling to 125% but don't know if that was the cause.

**Comment by zerebos** [comment]
Yes scaling can cause that

**Comment by snappyapple632** [comment]
Going into Properties>Compatitability>Change high DPI settings>High DPI scaling override and setting it to "System" or "System (Enhanced) seems to fix the issue. Easier than changing it in the Settings app.
