### ISSUE TITLE
(bug)BBD crashes upon pasting

### ISSUE THREAD

**Issue by R281** [rauenzi/BBDInstaller#30]
when i paste anything in the text input box(link, text, etc.) bandagedbd instantly crashes(CTRL +V or normal paste, doesnt matter, same with any other hotkey, like DEL + LMB while using Quick Delete Messages v1.4.2, and many many many more)
i have these plugins:
AccountDetailsPlus v0.1.10
BDFDB v1.4.3
BetterFormattingRedux v2.3.10
CharCounter v1.5.0
CompleteTimestamps v1.5.2
CopyRawMessage v1.1.2
CreationDate v1.4.0
Direct-Download v0.4.2
Edit Uploads v0.0.9
EmojiUtilities v0.0.9
Game Activity Toggle v1.2.6 
ImageToClipboard v0.3.5 
MessageLoggerV2 v1.7.68
MobileForAll v1.0.1 
PermissionsViewer v0.1.16
Quick Delete Messages v1.4.2
ServerCounter v1.0.3
ServerDetails v1.0.4
ShowHiddenChannels v2.9.3
TypingIndicator v0.5.1
VoiceUsersCounter v2.0.0
XenoLib v1.3.35
ZeresPluginLibrary v1.2.28
and these themes(not sure if this matters but):
MinimalCord v2.0.0
ServerColumns v1.0.6

**Comment by scrable** [comment]
I had the same issue. I reinstalled and it seems to be fine so far.

**Comment by R281** [comment]
thanks, it worked
