### ISSUE TITLE
Copy and Paste closes discord due to BandagedBD installation

### ISSUE THREAD

**Issue by ghost** [rauenzi/BBDInstaller#31]
I opened discord, tried to copy and paste a link to a friend and it immediately closed, and this happened after discord had an update, I looked it up and recent reddit posts from 2-3 days ago from now had people having this issue, they were told its because they are breaking TOS and should uninstall any mods, I did so and the issue stopped immediately, I guess discord updated to get rid of any modifications, is there a fix to this? Would BandagedBD have to be updated?

**Comment by dudeedud4** [comment]
Reinstall BBD. It will fix the issue.

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
