### ISSUE TITLE
Better Discord not working with PTB 

### ISSUE THREAD

**Issue by lxciper** [rauenzi/BBDInstaller#33]
PTB isn't working with better discord, and I no longer can enjoy it :crying_cat_face:

**Comment by KushinaAtori** [comment]
Same here made sure to completely un install discord and its trace files. Can indeed confirm this is a breaking bug. Unable to work with what it seems all clients. Only tested DiscordApp and PTB Discord

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
