### ISSUE TITLE
No longer working for me at all.

### ISSUE THREAD

**Issue by CheckisCheck** [rauenzi/BBDInstaller#34]
So today BD just went away happens every once in a while so I open BBD and install it and it just opens the web browser version of discord but in the client. I tried doing repair and on canary but it did the same thing each time. It would be much appreciated if you could help me.

**Comment by KushinaAtori** [comment]
Same here made sure to completely un install discord and its trace files. Can indeed confirm this is a breaking bug.

**Comment by KushinaAtori** [comment]
Seems to be fixed for me. 

![image](https://user-images.githubusercontent.com/80189479/112248805-93b8b880-8c24-11eb-964a-917ce9151745.png)

**Comment by GamingCoookie** [comment]
I can't get BBD installed either anymore. It doesn't turn into a browser instance for me but it just doesn't load.

Stable 80756 (2758037)
Host 1.0.9001
Windows 10 64-bit (10.0.19042)

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
