### ISSUE TITLE
BBD Installation Error

### ISSUE THREAD

**Issue by KushinaAtori** [rauenzi/BBDInstaller#35]
Using the latest 

- Injector (BBD v1.0.5 )
- Discord App: Latest
- PTB Discord: 1.0.1005
Whist installing Bandage Better Discord it kills processes normally and restarts. When restarting Discord PTB takes on the Mobile Site of Discord.

![image](https://user-images.githubusercontent.com/80189479/112248678-53593a80-8c24-11eb-83f2-919de40a1ba5.png)

Discord App: Bug seems to be fixed I guess? 3/23/2021

@rauenzi

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
