### ISSUE TITLE
"ReferenceError: Cannot access 'fs' before initialization"

### ISSUE THREAD

**Issue by uhhhhh123** [rauenzi/BBDInstaller#36]
I had This on my imac and today it removed so i was gonna get it back and when i tried to install it this showed "ReferenceError: Cannot access 'fs' before initialization" how can I fix cus I want it for discord & when I remove it to download it back the same thing pops up & wont do anything
<img width="728" alt="Screen Shot 2021-03-24 at 4 47 07 PM" src="https://user-images.githubusercontent.com/78468878/112381117-9668eb80-8cc0-11eb-8f3a-8f7dbc7266ca.png">
<img width="753" alt="Screen Shot 2021-03-24 at 4 47 11 PM" src="https://user-images.githubusercontent.com/78468878/112381132-99fc7280-8cc0-11eb-80a2-9bceb3d45733.png">

**Comment by sidbmw** [comment]
Same here

**Comment by ExecutionSpeed** [comment]
Same issue here.
<img width="912" alt="Screen Shot 2021-03-24 at 5 16 50 PM" src="https://user-images.githubusercontent.com/71984529/112384445-d0d48780-8cc4-11eb-9764-9fbf737dfa14.png">
<img width="912" alt="Screen Shot 2021-03-24 at 5 16 55 PM" src="https://user-images.githubusercontent.com/71984529/112384451-d29e4b00-8cc4-11eb-93cd-995897af08d9.png">

**Comment by Paulxxxxxxxxxx** [comment]
I'm having the same problem.

**Comment by PythonCoderAS** [comment]
Same problem.

**Comment by tominabox1** [comment]
having this issue on macOS Big Sur 11.3 Beta (20E5210c)

**Comment by jfurmancom** [comment]
Same here - Big Sur 11.1

**Comment by kiaralol** [comment]
yeah i randomly lost bd then tried redownloading it and it did the same thing

**Comment by ant-ms** [comment]
same for me (MacOS Big Sur)

**Comment by HandsomeMadMario** [comment]
same, seems to just be a mac problem. guess we'll just have to wait and see if it'll get fixed sooner or later. inb4 discord fucked with the API for the 17th time this attosecond.

**Comment by wxllow** [comment]
same

**Comment by xinyiiii** [comment]
When I click "reinstall" it just won't work

**Comment by Izanagis** [comment]
Same here, MacOSX 10.13.6 (High Sierra),  Intel i7-2600S @ 2.80Ghz (4 Core 8 Thread), AMD Radeon HD 6770M.
I've pointed to the direct path to the Discord.app file (~/Applications/Discord.app/), doesn't fix it either. A thing i find interesting is the focused application info in the top left shows "Discord" as the BD Installers name. Before this error, it showed "BandagedBD" (Discord wasn't open at the time btw).

https://user-images.githubusercontent.com/66091556/112552105-7e0bd600-8d7f-11eb-8934-fd7a63b70e50.mp4

**Comment by sekosama** [comment]
Same, I'm also experiencing the same difficulties. Is there any way to fix it and enjoy discord with a nice and cool background again?

**Comment by HandsomeMadMario** [comment]
> Same here, MacOSX 10.13.6 (High Sierra), Intel i7-2600S @ 2.80Ghz (4 Core 8 Thread), AMD Radeon HD 6770M.
> I've pointed to the direct path to the Discord.app file (~/Applications/Discord.app/), doesn't fix it either. A thing i find interesting is the focused application info in the top left shows "Discord" as the BD Installers name. Before this error, it showed "BandagedBD" (Discord wasn't open at the time btw).
> 
>  2021-03-25_15-32-44.mp4

i love your background

**Comment by Izanagis** [comment]
![him](https://user-images.githubusercontent.com/66091556/112704056-884cd380-8e56-11eb-83c7-e4e00076e88d.png)
> > Same here, MacOSX 10.13.6 (High Sierra), Intel i7-2600S @ 2.80Ghz (4 Core 8 Thread), AMD Radeon HD 6770M.
> > I've pointed to the direct path to the Discord.app file (~/Applications/Discord.app/), doesn't fix it either. A thing i find interesting is the focused application info in the top left shows "Discord" as the BD Installers name. Before this error, it showed "BandagedBD" (Discord wasn't open at the time btw).
> > 2021-03-25_15-32-44.mp4
> 
> i love your background

tech tips

**Comment by KushinaAtori** [comment]
This could be somehow related to an issue indicated over here. #33 

Edit: Or related to #35

**Comment by Izanagis** [comment]
> This could be somehow related to an issue indicated over here. #33
> 
> Edit: Or related to #35

I'm not using the PTB, The installer gives no details or info on what is happening either.

**Comment by halian** [comment]
Am having the same issue on Mac OS 11.2.1 “Big Sur”. Redownloading the installer does not cause a change in behavior.

**Comment by KushinaAtori** [comment]
Did you delete the trace files it leaves behind when
 you install Discord. Similar to this? 
![image](https://user-images.githubusercontent.com/80189479/112708263-fb6a4000-8e7e-11eb-8adf-04b546b5c60b.png)
![image](https://user-images.githubusercontent.com/80189479/112708267-002ef400-8e7f-11eb-81ac-62a1625b5e8f.png)


Edit: You must also uninstall it using BDD installer.

**Comment by Izanagis** [comment]
> Did you delete the trace files it leaves behind when
> you install Discord. Similar to this?
> ![image](https://user-images.githubusercontent.com/80189479/112708263-fb6a4000-8e7e-11eb-8adf-04b546b5c60b.png)
> ![image](https://user-images.githubusercontent.com/80189479/112708267-002ef400-8e7f-11eb-81ac-62a1625b5e8f.png)
> 
> Edit: You must also uninstall it using BDD installer.

This is a mac issue here, i've deleted the trace files in Application Support, still has the same issue. I don't think windows tips are going to help here man. It's a issue with the mac BD installer.
The main issue here is the BD installer not working on macos. You can't uninstall anything with it, it is unable to do anything. Maybe stay out if you're going to show tips for windows users.

**Comment by KushinaAtori** [comment]
> > Did you delete the trace files it leaves behind when
> > you install Discord. Similar to this?
> > ![image](https://user-images.githubusercontent.com/80189479/112708263-fb6a4000-8e7e-11eb-8adf-04b546b5c60b.png)
> > ![image](https://user-images.githubusercontent.com/80189479/112708267-002ef400-8e7f-11eb-81ac-62a1625b5e8f.png)
> > Edit: You must also uninstall it using BDD installer.
> 
> This is a mac issue here, i've deleted the trace files in Application Support, still has the same issue. I don't think windows tips are going to help here man. It's a issue with the mac BD installer.
> The main issue here is the BD installer not working on macos. You can't uninstall anything with it, it is unable to do anything. Maybe stay out if you're going to show tips for windows users.

I think you need to chill out. You're tweaking over a discord modifier. 😂 Just wait until someone like the developer for this to fix it.

**Comment by SamHep0803** [comment]
having the same issue, any updates on this?

**Comment by PythonCoderAS** [comment]
@SamHep0803 a fix has been linked here: https://github.com/rauenzi/BetterDiscordApp/issues/600#issuecomment-807927487.

I recommend deleting `/Applications/Discord.app` completely and re-downloading Discord.

**Comment by wxllow** [comment]
I've tried installing it manually and no luck either, bbd doesnt load when i launch discord.

Edit: 

> Samuel Hepworth a fix has been linked here: [rauenzi/BetterDiscordApp#600 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/600#issuecomment-807927487).
> 
> I recommend deleting `/Applications/Discord.app` completely and re-downloading Discord.

this works, i had to turn my plugins and themes back on tho

**Comment by Avakining** [comment]
> @SamHep0803 a fix has been linked here: [rauenzi/BetterDiscordApp#600 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/600#issuecomment-807927487).
> 
> I recommend deleting `/Applications/Discord.app` completely and re-downloading Discord.

Didn't work for me. I deleted every discord file (complete reinstall of discord), then tried to install BD, still failed in the exact same way.

**Comment by shiypc** [comment]
> @SamHep0803 a fix has been linked here: [rauenzi/BetterDiscordApp#600 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/600#issuecomment-807927487).
> 
> I recommend deleting `/Applications/Discord.app` completely and re-downloading Discord.

doesn't work on catalina 10.15.7

**Comment by tropicaaal** [comment]
Use the new cross-platform installer found here => https://github.com/betterdiscord/installer

**Comment by shiypc** [comment]
> Use the new cross-platform installer found here => https://github.com/betterdiscord/installer

works amazing for me, also kudos to them for updating the installer to look nicer

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
