### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by Pishgrumpy** [rauenzi/BBDInstaller#37]
When i download BBD everything is working fine. But as soon as i restart my PC, It tells me that "An error has occured. Unexcpected Token config.json Appdata>Local>Discord>app-0.0.309>resources>app>betterdiscord" I really find that annoying. but when i reinstall BBD everything works fine but its the same problem again when i restart my pc

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
