### ISSUE TITLE
Injector update loop

### ISSUE THREAD

**Issue by tycrek** [rauenzi/BBDInstaller#38]
Using the latest installer, I get this message when Discord launches:

```
There is an update available for BandagedBD's Injector (1.0.0). You can either update and restart now, or later.
```

If I click the shiney button that applies the update, Discord restarts.... and prompts me again. To be quite honest I'm unsure if this is a legitimate issue or an April 1st thing.

**Comment by Morinth20** [comment]
I've been having the exact same issue. I have uninstalled and re-installed 2-3 times as well in hopes that it would fix but it's still on that same issue.

**Comment by tropicaaal** [comment]
Use the new cross-platform installer found here => https://github.com/betterdiscord/installer

**Comment by seagull** [comment]
That is for a different product.

**Comment by Minecodes** [comment]
I have the same problem and used the latest installer of BD

**Comment by SilverlightPony** [comment]
> That is for a different product.

Rauenzi (creator of BandagedBD) also contributes to that project--and in fact is the individual who pushed the latest release of that project 4 days ago.

**Comment by tropicaaal** [comment]
> That is for a different product.

This is not for a different product. The new installer is built (and maintained) by the same people. It is designed to be cross-platform and easier to use and will eventually replace the current one in this repository.

**Comment by tropicaaal** [comment]
To provide context here, the self-updater on the `stable` branch of BandagedBD is currently broken and will do nothing upon clicking the update button. The intended behavior would be to install the new `restructure` version of BD, however that is (as stated before) broken. The installer I linked installs the new restructure branch therefore stopping the update notice.

**Comment by seagull** [comment]
I understand. I see you're heavily involved with this project. Thanks for clearing this up. I hope you can appreciate how confusing it is from an end-user's perspective but this is indeed the right answer.

**Comment by Zutyosh** [comment]
I just installed this new version and it works very well and there is no more bug.

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
