### ISSUE TITLE
Overlapped server icons in minimal mode.

### ISSUE THREAD

**Issue by anchuin** [rauenzi/BBDInstaller#9]
Enabling minimal mode causes the server icons to be "behind" the channel list of the active server.

Tried fully reinstalling Discord and BBD. I'm on the newest version for both Discord (Stable 64675 (92c9fdf)) and BBD (BBD 0.3.5/ Installer version 1.0.5) No custom themes or CSS is in use.

![grafik](https://user-images.githubusercontent.com/2878829/89576909-35bf9800-d830-11ea-8397-66d1c33199c4.png)

**Comment by laendle** [comment]
This repo is solely for the BBDInstaller and not for any issue inside the application. The issue here relates to the application and not the installer, this is why there was no response.
